name: Run Cypress Tests Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch:

jobs:

  prepare-and-run-tests:
    name: Prepare Environment and Run Cypress Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec:
          - authentication
          - sortingFunctionality
          - shoppingCartFunctionality
          - checkoutProcess

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests for ${{ matrix.spec }}
        id: cypress_run
        run: |
          CONFIG_OPTIONS="screenshotsFolder=results/screenshots/${{ matrix.spec }},video=true,videosFolder=results/videos/${{ matrix.spec }},requestTimeout=90000,responseTimeout=90000,defaultCommandTimeout=90000"

          npx cypress run \
            --spec "cypress/e2e/${{ matrix.spec }}/${{ matrix.spec }}.cy.ts" \
            --reporter mochawesome \
            --reporter-options "reportDir=results/reports,overwrite=false,html=false,json=true" \
            --config "${CONFIG_OPTIONS}"
        continue-on-error: true

      - name: Upload Combined Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: combined-test-artifacts-${{ matrix.spec }}
          path: |
            results/reports/
            results/screenshots/${{ matrix.spec }}/
            results/videos/${{ matrix.spec }}/
          retention-days: 7

