name: Run Cypress Tests Daily

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 00:00 UTC
  workflow_dispatch:

jobs:

  prepare-and-run-tests:
    name: Prepare Environment and Run Cypress Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec:
          - authentication
          - sortingFunctionality
          - shoppingCartFunctionality
          - checkoutProcess

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests for ${{ matrix.spec }}
        id: cypress_run
        run: |
          CONFIG_OPTIONS="screenshotsFolder=results/screenshots/${{ matrix.spec }},video=true,videosFolder=results/videos/${{ matrix.spec }},requestTimeout=90000,responseTimeout=90000,defaultCommandTimeout=90000"

          npx cypress run \
            --spec "cypress/e2e/${{ matrix.spec }}/${{ matrix.spec }}.cy.ts" \
            --config "${CONFIG_OPTIONS}"
        continue-on-error: true

      - name: Upload Test Artifacts for ${{ matrix.spec }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.spec }}-test-artifacts
          path: |
            results/reports/
            results/screenshots/${{ matrix.spec }}/
            results/videos/${{ matrix.spec }}/
          retention-days: 7


  consolidate-reports:
    name: Consolidate Reports and Generate HTML
    runs-on: ubuntu-latest
    needs: prepare-and-run-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all test artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-test-artifacts

      - name: Install mochawesome tools
        run: npm install mochawesome-merge mochawesome-report-generator

      - name: List JSON reports
        run: find all-test-artifacts -name "*.json"

      - name: Merge mochawesome reports
        run: |
          mkdir -p merged_reports
          find all-test-artifacts -name "*.json" -exec cp {} merged_reports/ \;

          echo "Running mochawesome-merge..."
          npx mochawesome-merge merged_reports/*.json > cypress-combined-report.json

      - name: Generate combined HTML report
        run: |
          mkdir -p results/combined-html-report
          npx marge cypress-combined-report.json -o results/combined-html-report

      - name: Upload Combined HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: combined-mochawesome-html-report
          path: results/combined-html-report/
          retention-days: 7
